-- UniSafe Sample Data
-- This script inserts sample data for testing and development

-- Insert sample Reddit posts
INSERT INTO reddit_posts (id, title, selftext, author, created_utc, score, num_comments, url, permalink, subreddit, processed) VALUES
('sample001', 'UDM Pro firmware 3.2.7 causing constant disconnects', 'After updating to firmware 3.2.7, my UDM Pro keeps disconnecting clients every few minutes. Anyone else experiencing this?', 'unifi_user_01', EXTRACT(EPOCH FROM NOW() - INTERVAL '2 days'), 15, 8, 'https://reddit.com/r/UNIFI/posts/sample001', '/r/UNIFI/comments/sample001/', 'UNIFI', false),
('sample002', 'U6 Lite firmware 6.5.55 WiFi issues', 'Updated my U6 Lite access points to 6.5.55 and now devices can''t maintain stable connections. Constant reconnecting.', 'wifi_admin', EXTRACT(EPOCH FROM NOW() - INTERVAL '1 day'), 23, 12, 'https://reddit.com/r/UNIFI/posts/sample002', '/r/UNIFI/comments/sample002/', 'UNIFI', false),
('sample003', 'USW Pro 24 firmware 6.5.59 port issues', 'Since updating to firmware 6.5.59, some ports on my USW Pro 24 are not providing PoE power properly.', 'network_eng', EXTRACT(EPOCH FROM NOW() - INTERVAL '3 hours'), 8, 5, 'https://reddit.com/r/UNIFI/posts/sample003', '/r/UNIFI/comments/sample003/', 'UNIFI', false),
('sample004', 'UXG Pro firmware 3.2.5 - working great!', 'Just wanted to say that the UXG Pro firmware 3.2.5 is running perfectly for me. No issues at all.', 'happy_user', EXTRACT(EPOCH FROM NOW() - INTERVAL '6 hours'), 12, 3, 'https://reddit.com/r/UNIFI/posts/sample004', '/r/UNIFI/comments/sample004/', 'UNIFI', false);

-- Insert sample firmware issues (these would normally be generated by the analysis engine)
INSERT INTO firmware_issues (post_id, equipment_type, firmware_version, issue_type, severity, description, extracted_from) VALUES
('sample001', 'UDM Pro', '3.2.7', 'connectivity', 'high', 'Constant client disconnections after firmware update', 'After updating to firmware 3.2.7, my UDM Pro keeps disconnecting clients every few minutes'),
('sample002', 'U6 Lite', '6.5.55', 'wifi', 'high', 'WiFi devices unable to maintain stable connections', 'Updated my U6 Lite access points to 6.5.55 and now devices can''t maintain stable connections'),
('sample003', 'USW Pro 24', '6.5.59', 'power', 'medium', 'PoE power delivery issues on some ports', 'some ports on my USW Pro 24 are not providing PoE power properly');

-- Insert sample risk assessments
INSERT INTO risk_assessments (equipment_type, firmware_version, risk_percentage, severity, issue_count) VALUES
('UDM Pro', '3.2.7', 85, 'high', 1),
('U6 Lite', '6.5.55', 90, 'high', 1),
('USW Pro 24', '6.5.59', 65, 'medium', 1),
('UXG Pro', '3.2.5', 15, 'low', 0);

-- Insert sample scan results
INSERT INTO scan_results (timestamp, posts_scanned, issues_found, scan_duration_ms, success) VALUES
(EXTRACT(EPOCH FROM NOW() - INTERVAL '1 hour'), 25, 3, 1250, true),
(EXTRACT(EPOCH FROM NOW() - INTERVAL '7 hours'), 18, 2, 980, true),
(EXTRACT(EPOCH FROM NOW() - INTERVAL '13 hours'), 32, 4, 1650, true);
